
import React from "react";
import "./About.css";

function AboutPage() {
  return (
    <section className="about-section">
      <div className="container">
        <div className="team__content">
          <h6 className="subtitle">Welcome to PredictiX</h6>

          <h2>
            About <span className="highlight">PredictiX</span>
          </h2>

          <p className="description">
            PredictiX is an AI-powered healthcare platform that leverages
            Machine Learning to analyze symptoms, assess health risks, and
            provide disease predictions. Built using the MERN Stack and
            Python-based ML models, the platform aims to make health insights
            more accessible while promoting early awareness and preventive
            care.
          </p>
        </div>

        <div className="about-content">
          <div className="about-card">
            <h3>🎯 Project Objective</h3>
            <p>
              PredictiX aims to assist users in identifying potential health
              conditions using Machine Learning models trained on medical data.
              The platform helps users understand possible diseases and
              encourages timely medical consultation.
            </p>
          </div>

          <div className="about-card">
            <h3>🚀 Key Features</h3>
            <ul>
              <li>AI-Based Disease Prediction</li>
              <li>Heart Disease Risk Assessment</li>
              <li>Diabetes Prediction</li>
              <li>Medical Report Analysis</li>
              <li>Secure User Authentication</li>
              <li>Personalized Health Recommendations</li>
              <li>Responsive Dashboard</li>
            </ul>
          </div>

          <div className="about-card">
            <h3>🛠 Technology Stack</h3>
            <ul>
              <li>
                <strong>Frontend:</strong> React.js, CSS3
              </li>
              <li>
                <strong>Backend:</strong> Node.js, Express.js
              </li>
              <li>
                <strong>Database:</strong> MongoDB
              </li>
              <li>
                <strong>Machine Learning:</strong> Python, Scikit-Learn
              </li>
              <li>
                <strong>Data Processing:</strong> Pandas, NumPy
              </li>
              <li>
                <strong>Authentication:</strong> JWT
              </li>
            </ul>
          </div>

          <div className="about-card">
            <h3>📈 Prediction Process</h3>
            <p>
              Users provide symptoms or upload medical reports. The system
              processes the input using trained Machine Learning models and
              generates predictions along with relevant health insights.
            </p>
          </div>

          <div className="about-card developer-card">
            <h3>👨‍💻 Developer</h3>

            <p className="developer-name">Yuvaraj M</p>

            <p>
              Full Stack Developer and Data Science enthusiast with expertise
              in MERN Stack, Java, Python, Machine Learning, and AI-driven
              healthcare applications.
            </p>
          </div>

          <div className="about-card">
            <h3>⚠ Disclaimer</h3>
            <p>
              PredictiX is designed for educational and informational
              purposes. Predictions generated by the system should not be
              considered a substitute for professional medical advice,
              diagnosis, or treatment. Always consult qualified healthcare
              professionals for medical concerns.
            </p>
          </div>
        </div>
      </div>
    </section>
  );
}

export default AboutPage;

